### PR TITLE
Just a few lines of code -- sklearn stuff I was playing around with.

### PR DESCRIPTION
**Pull request by chbrown**
And can you make us contributors on this project?

### CODE REVIEW

**Comment by aronwc** [comment]
Cool -- note that CountVectorizer has a .vocabulary_ property, so you may be able to remove the Dictionary bit.

**Comment by aronwc** [comment]
You should be able to contribute to tweedr now.

**Comment by chbrown** [comment]
Cool, thanks. Yes, the Dictionary was cruft from a previous project -- kind of surprised though that `CountVectorizer` can't be fitted incrementally (i.e., document by document rather than in one pass)?

**Comment by aronwc** [comment]
Re: CountVectorizer: Yes, I think that's to support all the thresholding operations (e.g., min_df, max_df), which don't make sense in a streaming context.

If raw data doesn't fit in memory, makes sense to have tokenization be a separate step. Then pass the vocabulary to CountVectorizer constructor.

**Pull request merged**
